version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8180:8080"
    volumes:
      - ./src/backend/data:/pb/pb_data
      - ./src/backend/hooks:/pb/pb_hooks
      - ./src/backend/migrations:/pb/pb_migrations
    restart: unless-stopped
