
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/app/pb_data
      - ./backend/pb_migrations:/app/pb_migrations
      - ./backend/sf_logs:/app/sf_logs
    restart: unless-stopped
